# Generated by Django 5.0.4 on 2024-07-11 11:28

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Joylinks_Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tg_id', models.SlugField(unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('tg_full_name', models.CharField(max_length=255)),
                ('tg_username', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(max_length=120)),
                ('district', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=13)),
                ('call_state', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('off_state', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_ban', models.BooleanField(default=False)),
                ('is_admin', models.CharField(default='A', max_length=2)),
                ('course_id', models.ManyToManyField(blank=True, null=True, to='Joylinks_Courses.courses')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
